Fake NEWS CLASSIFIER USING LSTM

In [1]:
import pandas as pd

importing the dataset

In [2]:
df_news=pd.read_csv('train.csv')

In [3]:
df_news.head(10)

id                                              title  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2   2                  Why the Truth Might Get You Fired   
3   3  15 Civilians Killed In Single US Airstrike Hav...   
4   4  Iranian woman jailed for fictional unpublished...   
5   5  Jackie Mason: Hollywood Would Love Trump if He...   
6   6  Life: Life Of Luxury: Elton John’s 6 Favorite ...   
7   7  Benoît Hamon Wins French Socialist Party’s Pre...   
8   8  Excerpts From a Draft Script for Donald Trump’...   
9   9  A Back-Channel Plan for Ukraine and Russia, Co...   

                         author  \
0                 Darrell Lucus   
1               Daniel J. Flynn   
2            Consortiumnews.com   
3               Jessica Purkiss   
4                Howard Portnoy   
5               Daniel Nussbaum   
6                           NaN   
7               Alissa J. Rubin   
8                           NaN   
9  Megan Twohey and Scott Shane   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1  
5  In these trying times, Jackie Mason is the Voi...      0  
6  Ever wonder how Britain’s most iconic pop pian...      1  
7  PARIS  —   France chose an idealistic, traditi...      0  
8  Donald J. Trump is scheduled to make a highly ...      0  
9  A week before Michael T. Flynn resigned as nat...      0

In [4]:
## drop na values
df_news=df_news.dropna()

In [5]:
## get the independent featureso of the dataset
X= df_news.drop('label',axis=1)

In [6]:
## Get the Dependent features
y=df_news['label']

In [7]:
X.shape

(18285, 4)

In [8]:
y.shape

(18285,)

In [9]:
import tensorflow as tf

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [11]:
### Vocabulary size
voc_size=5000

ONE HOT REPRESENTATION

In [12]:
messages=X.copy()

In [14]:
messages['title'][2]

'Why the Truth Might Get You Fired'

In [16]:
messages.reset_index(inplace=True)

In [17]:
import nltk
import re
from nltk.corpus import stopwords

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [19]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [20]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [21]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[821, 2095, 4935, 2373, 4852, 2883, 2614, 4179, 1140, 4653],
 [3245, 1840, 41, 3895, 473, 246, 1186],
 [4847, 2441, 2134, 3685],
 [3409, 1809, 632, 4074, 3683, 3134],
 [982, 473, 3075, 3668, 2702, 1164, 473, 1185, 1068, 1711],
 [2071,
  4534,
  665,
  4669,
  4643,
  1575,
  4063,
  173,
  1742,
  4013,
  4838,
  3067,
  2532,
  4452,
  1186],
 [1549, 1189, 1651, 2666, 4443, 720, 3906, 4089, 4406, 660, 3530],
 [3908, 989, 3185, 1931, 4284, 4741, 1575, 2909, 4406, 660, 3530],
 [2242, 3976, 3761, 4215, 2769, 2168, 1820, 4224, 1575, 2185],
 [3644, 497, 998, 2923, 3087, 4788, 2803, 4837],
 [1540, 3493, 856, 165, 893, 3220, 1332, 2138, 4073, 4960, 3774],
 [4074, 1171, 4852, 2168, 1575, 4284],
 [1469, 3669, 2354, 832, 620, 904, 3101, 260, 2052],
 [1585, 143, 3876, 4761, 3056, 1802, 2706, 4406, 660, 3530],
 [3101, 4540, 2704, 3058, 3944, 4406, 660, 3530],
 [2171, 1922, 3494, 4177, 4066, 834, 2872, 1568, 383, 4019],
 [2, 1889, 1840],
 [2735, 2976, 2596, 466, 1575, 3782, 5, 1186],
 [2515, 1195

EMBEDDED REPRESENTATION

In [22]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4179 1140 4653]
 [   0    0    0 ...  473  246 1186]
 [   0    0    0 ... 2441 2134 3685]
 ...
 [   0    0    0 ... 4406  660 3530]
 [   0    0    0 ... 1157 2978 3412]
 [   0    0    0 ...  243 4916  730]]


In [23]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  821,
       2095, 4935, 2373, 4852, 2883, 2614, 4179, 1140, 4653], dtype=int32)

In [24]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [25]:
len(embedded_docs),y.shape

(18285, (18285,))

In [26]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [27]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

MODEL TRAINING

In [29]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 11s 44ms/step - loss: 0.3381 - accuracy: 0.8380 - val_loss: 0.2057 - val_accuracy: 0.9145
Epoch 2/10
192/192 [==============================] - 7s 35ms/step - loss: 0.1450 - accuracy: 0.9417 - val_loss: 0.2059 - val_accuracy: 0.9165
Epoch 3/10
192/192 [==============================] - 9s 48ms/step - loss: 0.1044 - accuracy: 0.9624 - val_loss: 0.2134 - val_accuracy: 0.9157
Epoch 4/10
192/192 [==============================] - 7s 35ms/step - loss: 0.0769 - accuracy: 0.9724 - val_loss: 0.2698 - val_accuracy: 0.9092
Epoch 5/10
192/192 [==============================] - 9s 45ms/step - loss: 0.0578 - accuracy: 0.9793 - val_loss: 0.2903 - val_accuracy: 0.9147
Epoch 6/10
192/192 [==============================] - 8s 42ms/step - loss: 0.0379 - accuracy: 0.9875 - val_loss: 0.3706 - val_accuracy: 0.9046
Epoch 7/10
192/192 [==============================] - 8s 43ms/step - loss: 0.0282 - accuracy: 0.9916 - val_loss: 0.4298 - val_accuracy: 0.908

ADDING DROPOUT

In [ ]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])